name: goreleaser

on:
  workflow_dispatch:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Make All
        run: |
          ./package.sh

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: tiny-frpc
          path: release/
